/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 31
#define YY_END_OF_BUFFER 32
static yyconst short int yy_accept[426] =
    {   0,
       12,   12,   32,   31,   12,   12,   20,   31,    1,    8,
       30,   31,   18,   31,   28,   28,   28,   28,   28,   28,
       28,   28,   31,   12,   12,    0,   17,    0,    0,    0,
        0,    0,    0,    0,   18,    6,    2,   28,   28,    0,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   26,
        0,    0,    0,   12,    0,   21,    0,    0,    0,    0,
        0,   19,   18,    6,    6,    6,   28,   28,   28,    0,
        0,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   12,    0,    0,    0,    0,    0,    0,    0,
        0,   18,    6,    6,    6,    6,    6,    6,   28,   28,

       28,   28,   28,   29,   28,   28,   28,    7,   28,   28,
       28,   28,   14,   28,   28,   25,   28,    0,   23,   22,
       18,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,   28,   28,   28,   28,   28,   28,   28,   28,
        4,   28,   28,   28,   11,   28,   28,   28,   27,   18,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,    9,
       28,   28,   28,   28,   28,   18,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,

        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,    5,   10,   13,   28,   28,
       28,   18,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,    3,   15,   28,   24,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,

        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,

        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    1,    1,    6,    1,    7,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   17,    1,    1,
       18,    1,    1,    1,   19,   20,   21,   22,   23,   24,
       25,   20,   26,   20,   20,   27,   28,   29,   30,   31,
       32,   33,   34,   35,   36,   37,   20,   20,   20,   20,
       38,    1,   39,    1,    1,    1,   20,   20,   20,   20,

       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   40,    1,   41,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[42] =
    {   0,
        1,    1,    2,    1,    2,    1,    1,    1,    1,    1,
        1,    3,    1,    1,    1,    4,    1,    1,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    5,    1,    1,
        1
    } ;

static yyconst short int yy_base[560] =
    {   0,
        0,    0,  884,  885,   40,  879,  885,  875,  885,  885,
      885,   22,   37,  863,   30,   31,   38,   42,   40,   39,
       51,   59,   59,   81,  876,  872,  885,  852,  863,  851,
       62,  856,  838,  857,   74,  856,  885,   54,   57,  855,
       71,   72,   75,   83,   63,   78,   86,   89,   96,  101,
      104,  120,  123,  111,  846,  885,  833,  103,  105,  838,
      853,  850,  116,  849,  848,  847,  102,  117,  120,  126,
      127,  131,  122,  130,  134,  154,  133,  138,  143,  157,
      159,  164,  822,  187,  847,  846,  845,  844,  843,  842,
      841,  132,  838,  837,  836,  835,  834,  833,  146,  158,

      163,  171,  175,  885,  184,  177,  182,  178,  183,  192,
      188,  198,  194,  215,  202,  201,  203,  235,  885,  885,
      211,  832,  831,  830,  829,  828,  827,  826,  825,  824,
      823,  822,  213,  226,  227,  228,  229,  230,  231,  232,
      233,  236,  240,  247,  241,  242,  265,  267,  244,  238,
      821,  820,  819,  818,  817,  816,  815,  814,  813,  812,
      811,  810,  809,  808,  807,  806,  805,  804,  246,  271,
      272,  273,  274,  276,  277,  278,  279,  283,  281,  285,
      288,  290,  306,  308,  309,  243,  803,  802,  801,  800,
      799,  798,  797,  796,  795,  794,  793,  792,  791,  790,

      789,  788,  787,  786,  785,  784,  783,  782,  781,  780,
      779,  778,  777,  291,  292,  311,  316,  317,  318,  320,
      322,  323,  324,  325,  327,  326,  329,  332,  334,  352,
      357,  362,  776,  775,  774,  773,  772,  771,  770,  769,
      768,  767,  766,  765,  764,  763,  762,  761,  760,  759,
      758,  757,  756,  755,  754,  753,  752,  751,  750,  749,
      748,  747,  746,  745,  744,  743,  742,  741,  740,  739,
      337,  343,  350,  361,  363,  364,  366,  367,  368,  369,
      370,  371,  373,  375,  376,  394,  377,  382,  738,  737,
      736,  735,  734,  733,  732,  731,  730,  729,  728,  727,

      726,  725,  724,  723,  722,  721,  720,  719,  718,  717,
      716,  715,  714,  713,  712,  711,  710,  709,  708,  707,
      706,  705,  704,  703,  702,  701,  700,  699,  698,  697,
      696,  695,  694,  693,  692,  691,  690,  689,  688,  380,
      381,  384,  387,  396,  400,  401,  404,  407,  408,  410,
      411,  687,  686,  412,  685,  417,  684,  683,  682,  681,
      680,  679,  678,  677,  676,  675,  674,  673,  672,  671,
      670,  669,  668,  667,  666,  665,  664,  663,  662,  661,
      660,  659,  658,  657,  656,  655,  654,  653,  652,  651,
      650,  649,  648,  647,  646,  645,  644,  643,  642,  641,

      640,  639,  638,  637,  636,  635,  634,  633,  632,  414,
      415,  419,  420,  421,  424,  425,  427,  428,  431,  435,
      438,  631,  630,  439,  885,  477,  480,  481,  486,  489,
      641,  490,  640,  493,  639,  638,  494,  496,  499,  637,
      636,  635,  634,  500,  502,  504,  507,  633,  632,  631,
      630,  629,  628,  627,  508,  510,  512,  514,  517,  626,
      625,  624,  623,  622,  621,  620,  619,  618,  617,  616,
      518,  520,  522,  524,  526,  529,  615,  614,  613,  612,
      611,  610,  609,  608,  607,  606,  605,  604,  603,  602,
      601,  600,  530,  532,  534,  536,  538,  540,  543,  599,

      598,  597,  596,  595,  594,  593,  592,  591,  590,  589,
      588,  587,  586,  585,  584,  583,  582,  581,  580,  579,
      578,  544,  546,  548,  550,  552,  554,  556,  559,  577,
      576,  575,  574,  475,  471,  470,  468,  467,  466,  464,
      463,  460,  457,  456,  452,  348,  347,  298,  292,  202,
      104,   55,  560,  562,  564,  566,  568,  570,  572
    } ;

static yyconst short int yy_def[560] =
    {   0,
      425,    1,  425,  425,  425,  425,  425,  426,  425,  425,
      425,  425,  427,  425,  428,  428,  428,  428,  428,  428,
      428,  428,  429,  425,  425,  426,  425,  425,  425,  425,
      425,  425,  425,  425,  430,  431,  425,  432,  432,  433,
      432,  432,  432,  432,  432,  432,  432,  432,  432,  432,
      429,  429,  425,  429,  425,  425,  425,  425,  425,  425,
      425,  425,  434,  435,  436,  436,  437,  438,  438,  425,
      433,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  425,  429,  425,  425,  425,  425,  425,  425,
      425,  439,  440,  441,  441,  442,  443,  443,  444,  445,

      446,  446,  445,  425,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  429,  425,  425,
      447,  448,  449,  449,  450,  451,  451,  452,  453,  454,
      454,  453,  455,  456,  457,  457,  458,  458,  456,  458,
      458,  458,  458,  458,  458,  458,  458,  458,  458,  459,
      460,  461,  461,  462,  463,  463,  464,  465,  466,  466,
      465,  467,  468,  469,  469,  470,  470,  468,  471,  472,
      473,  473,  474,  474,  475,  475,  472,  475,  475,  475,
      475,  475,  475,  475,  475,  476,  477,  478,  478,  479,
      480,  480,  481,  482,  483,  483,  482,  484,  485,  486,

      486,  487,  487,  485,  488,  489,  490,  490,  491,  491,
      492,  492,  489,  493,  494,  495,  495,  496,  496,  497,
      497,  498,  498,  494,  498,  498,  498,  498,  498,  498,
      498,  499,  500,  501,  501,  502,  503,  503,  504,  505,
      506,  506,  505,  507,  508,  509,  509,  510,  510,  508,
      511,  512,  513,  513,  514,  514,  515,  515,  512,  516,
      517,  518,  518,  519,  519,  520,  520,  521,  521,  517,
      522,  523,  524,  524,  525,  525,  526,  526,  527,  527,
      528,  528,  523,  528,  528,  528,  528,  529,  530,  531,
      531,  532,  533,  533,  534,  535,  536,  536,  535,  537,

      538,  539,  539,  540,  540,  538,  541,  542,  543,  543,
      544,  544,  545,  545,  542,  546,  547,  548,  548,  549,
      549,  550,  550,  551,  551,  547,  546,  547,  548,  548,
      549,  549,  550,  550,  551,  551,  552,  552,  547,  553,
      554,  555,  555,  556,  556,  557,  557,  558,  558,  559,
      559,  552,  552,  554,  552,  529,  530,  531,  531,  532,
      533,  533,  534,  535,  536,  536,  535,  537,  538,  539,
      539,  540,  540,  538,  541,  542,  543,  543,  544,  544,
      545,  545,  542,  546,  547,  548,  548,  549,  549,  550,
      550,  551,  551,  547,  546,  547,  548,  548,  549,  549,

      550,  550,  551,  551,  552,  552,  547,  552,  552,  553,
      554,  555,  555,  556,  556,  557,  557,  558,  558,  559,
      559,  552,  552,  554,    0,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,

      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425
    } ;

static yyconst short int yy_nxt[927] =
    {   0,
        4,    5,    5,    6,    4,    7,    8,    9,   10,    7,
        7,   11,    7,   12,    7,   13,   14,    4,   15,   15,
       15,   15,   16,   17,   15,   18,   19,   15,   15,   15,
       20,   15,   21,   22,   15,   15,   15,    4,    4,   23,
        4,   24,   24,   28,   29,   38,   38,   30,   34,   31,
       32,   33,   35,   38,   38,   38,   43,   38,  408,   41,
       52,   53,   46,   44,   42,   47,   38,   40,   40,   67,
       45,   48,   69,   49,   38,   40,   40,   40,   69,   40,
       58,   50,   24,   24,   59,   34,   69,   69,   40,   63,
       69,   40,   74,   69,   40,   75,   40,   77,   69,   54,

       40,   69,   72,   78,   69,   73,  425,  406,   40,   40,
       76,   69,   40,  425,   81,   40,   69,   99,   80,   79,
       40,   52,   53,   40,   53,   53,   40,   34,   87,   82,
       89,   92,  101,   40,   88,  103,   90,  101,   40,   40,
      106,   70,  425,   34,   54,  101,  101,  121,  101,  101,
       84,   54,  108,  101,   40,  112,  113,   40,  101,   40,
       54,  133,  107,   83,  104,  104,  105,   40,   40,  101,
       40,   40,  101,  135,  101,   40,  109,  114,  135,  101,
       40,  115,  117,   40,  110,  116,  138,  111,   52,   53,
      139,   40,  138,  138,   40,   40,   40,  138,  138,  138,

       40,   40,  140,  138,  142,  403,  141,  138,   40,  138,
      145,  143,   40,  138,   40,   40,  138,  138,  138,   40,
       40,   40,   34,  146,  144,   40,  150,   54,  169,   40,
      138,   40,  149,  147,  148,   40,   52,   53,   40,   40,
       40,  171,  171,  174,  175,  174,  177,  175,  175,   34,
       40,  175,   40,  186,   34,  175,  175,  175,  232,  175,
      178,  214,  175,   40,   40,   40,   40,   40,   40,   40,
       40,  180,  179,   40,  182,   54,  181,   40,   40,   40,
      175,   40,  175,   40,   40,  185,  216,  216,  219,  220,
      183,  219,  220,  223,  224,  402,  223,  184,  223,  226,

      223,  399,   40,  223,   40,  223,  271,  273,   40,   40,
       40,   40,  227,   40,   40,   40,   40,  225,   40,  228,
       40,  223,   40,  223,  223,   40,  273,   40,   40,   40,
      230,  276,  277,  276,  229,  277,  231,  280,  281,  280,
      283,  281,  281,   40,  281,   40,   40,  281,   40,  281,
      398,  396,  340,   40,   40,   40,  284,   40,  342,   40,
       40,   40,   40,   40,   40,  342,   40,  281,  285,   40,
      286,   40,  281,   34,   40,  287,  345,  288,  346,  345,
       40,  346,  349,  350,  349,  350,  353,   40,  354,   40,
      353,  353,  353,   34,   40,  410,  412,  356,   40,  412,

       40,   40,  415,   40,   40,   40,   40,   40,   40,  353,
       40,  416,   40,   40,   40,  415,  416,   40,   40,  419,
      355,   40,  420,  419,   40,  420,  423,  424,   34,  410,
      412,   40,  356,   40,  412,  415,  416,   40,   40,  415,
      416,   40,  419,  420,   40,   40,  419,   40,   40,   40,
      420,   40,   40,  423,  424,  392,   40,   40,   40,  391,
      388,   40,   40,  387,   40,   40,  385,  382,   40,  379,
      378,  376,   40,  372,  371,   40,   40,   26,  369,   26,
       26,   26,   36,   36,   39,   39,   51,   51,   51,   51,
       51,   64,   64,   68,   68,   93,   93,  100,  100,  102,

      102,  122,  122,  134,  134,  136,  136,  137,  137,  151,
      151,  170,  170,  172,  172,  173,  173,  176,  176,  187,
      187,  215,  215,  217,  217,  218,  218,  221,  221,  222,
      222,  233,  233,  272,  272,  274,  274,  275,  275,  278,
      278,  279,  279,  282,  282,  289,  289,  341,  341,  343,
      343,  344,  344,  347,  347,  348,  348,  351,  351,  352,
      352,  357,  357,  411,  411,  413,  413,  414,  414,  417,
      417,  418,  418,  421,  421,  422,  422,  366,  364,  361,
      359,  338,  335,  334,  331,  330,  328,  324,  323,  320,
      319,  317,  314,  311,  310,  308,  304,  303,  301,  298,

      296,  293,  291,  268,  267,  264,  263,  261,  258,  255,
      254,  252,  248,  247,  245,  242,  240,  237,  235,  212,
      209,  208,  206,  202,  201,  199,  196,  194,  191,  189,
      166,  165,  163,  160,  158,  155,  153,  131,  129,  126,
      124,   97,   95,   71,   66,  423,  409,  409,  409,  407,
      409,  405,  404,  405,  404,  401,  400,  401,  400,  397,
      397,  395,  407,  404,  405,  404,  401,  400,  401,  400,
      397,  397,  395,  394,  393,  390,  389,  390,  389,  386,
      386,  384,  383,  380,  381,  380,  377,  377,  375,  374,
      373,  370,  370,  368,  367,  365,  363,  362,  360,  358,

      409,  423,  409,  407,  409,  405,  404,  405,  404,  401,
      400,  401,  400,  397,  397,  395,  407,  404,  405,  404,
      401,  400,  401,  400,  397,  397,  395,  394,  393,  390,
      389,  390,  389,  386,  386,  384,  383,  380,  381,  380,
      377,  377,  375,  374,  373,  370,  370,  368,  367,  365,
      363,  362,  360,  358,  339,  336,  337,  336,  333,  332,
      333,  332,  329,  329,  327,  326,  325,  322,  321,  322,
      321,  318,  318,  316,  315,  312,  313,  312,  309,  309,
      307,  306,  305,  302,  302,  300,  299,  297,  295,  294,
      292,  290,  270,  269,  266,  265,  266,  265,  262,  262,

      260,  259,  256,  257,  256,  253,  253,  251,  250,  249,
      246,  246,  244,  243,  241,  239,  238,  236,  234,  213,
      210,  211,  210,  207,  207,  205,  204,  203,  200,  200,
      198,  197,  195,  193,  192,  190,  188,  168,  167,  164,
      164,  162,  161,  159,  157,  156,  154,  152,  132,  130,
      128,  127,  125,  123,  120,  119,  119,  119,  119,  119,
      119,  118,   98,   96,   94,   62,   56,   91,   86,   85,
       70,   65,   62,   61,   60,   57,   56,   55,   27,   25,
       37,   27,   25,  425,    3,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,

      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425
    } ;

static yyconst short int yy_chk[927] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    5,   12,   12,   15,   16,   12,   13,   12,
       12,   12,   13,   17,   20,   19,   17,   18,  552,   16,
       23,   23,   19,   17,   16,   19,   21,   15,   16,   38,
       18,   20,   39,   21,   22,   17,   20,   19,   45,   18,
       31,   22,   24,   24,   31,   35,   41,   42,   21,   35,
       43,   38,   42,   46,   39,   43,   22,   45,   44,   23,

       45,   47,   41,   46,   48,   41,   51,  551,   41,   42,
       44,   49,   43,   54,   49,   46,   50,   67,   48,   47,
       44,   52,   52,   47,   53,   53,   48,   63,   58,   50,
       59,   63,   68,   49,   58,   69,   59,   73,   50,   67,
       73,   70,   71,   92,   51,   74,   72,   92,   77,   75,
       54,   54,   75,   78,   68,   77,   78,   69,   79,   73,
       52,   99,   74,   53,   70,   71,   72,   74,   72,   76,
       77,   75,   80,  100,   81,   78,   76,   79,  101,   82,
       79,   80,   82,   99,   76,   81,  102,   76,   84,   84,
      103,   76,  106,  108,   80,  100,   81,  107,  109,  105,

      101,   82,  105,  111,  107,  550,  106,  110,  102,  113,
      111,  109,  103,  112,  106,  108,  116,  115,  117,  107,
      109,  105,  121,  112,  110,  111,  121,   84,  133,  110,
      114,  113,  117,  114,  115,  112,  118,  118,  116,  115,
      117,  134,  135,  136,  137,  138,  139,  140,  141,  150,
      133,  142,  114,  150,  186,  143,  145,  146,  186,  149,
      140,  169,  144,  134,  135,  136,  137,  138,  139,  140,
      141,  143,  142,  142,  146,  118,  144,  143,  145,  146,
      147,  149,  148,  169,  144,  148,  170,  171,  172,  173,
      147,  174,  175,  176,  177,  549,  179,  147,  178,  179,

      180,  548,  147,  181,  148,  182,  214,  215,  170,  171,
      172,  173,  181,  174,  175,  176,  177,  178,  179,  182,
      178,  183,  180,  184,  185,  181,  216,  182,  214,  215,
      184,  217,  218,  219,  183,  220,  185,  221,  222,  223,
      224,  226,  225,  183,  227,  184,  185,  228,  216,  229,
      547,  546,  271,  217,  218,  219,  225,  220,  272,  221,
      222,  223,  224,  226,  225,  273,  227,  230,  229,  228,
      230,  229,  231,  232,  271,  231,  274,  232,  275,  276,
      272,  277,  278,  279,  280,  281,  282,  273,  283,  230,
      284,  285,  287,  288,  231,  340,  341,  288,  274,  342,

      275,  276,  343,  277,  278,  279,  280,  281,  282,  286,
      283,  344,  284,  285,  287,  345,  346,  340,  341,  347,
      286,  342,  348,  349,  343,  350,  351,  354,  356,  410,
      411,  286,  356,  344,  412,  413,  414,  345,  346,  415,
      416,  347,  417,  418,  348,  349,  419,  350,  351,  354,
      420,  410,  411,  421,  424,  545,  412,  413,  414,  544,
      543,  415,  416,  542,  417,  418,  541,  540,  419,  539,
      538,  537,  420,  536,  535,  421,  424,  426,  534,  426,
      426,  426,  427,  427,  428,  428,  429,  429,  429,  429,
      429,  430,  430,  432,  432,  434,  434,  437,  437,  438,

      438,  439,  439,  444,  444,  445,  445,  446,  446,  447,
      447,  455,  455,  456,  456,  457,  457,  458,  458,  459,
      459,  471,  471,  472,  472,  473,  473,  474,  474,  475,
      475,  476,  476,  493,  493,  494,  494,  495,  495,  496,
      496,  497,  497,  498,  498,  499,  499,  522,  522,  523,
      523,  524,  524,  525,  525,  526,  526,  527,  527,  528,
      528,  529,  529,  553,  553,  554,  554,  555,  555,  556,
      556,  557,  557,  558,  558,  559,  559,  533,  532,  531,
      530,  521,  520,  519,  518,  517,  516,  515,  514,  513,
      512,  511,  510,  509,  508,  507,  506,  505,  504,  503,

      502,  501,  500,  492,  491,  490,  489,  488,  487,  486,
      485,  484,  483,  482,  481,  480,  479,  478,  477,  470,
      469,  468,  467,  466,  465,  464,  463,  462,  461,  460,
      454,  453,  452,  451,  450,  449,  448,  443,  442,  441,
      440,  436,  435,  433,  431,  423,  422,  409,  408,  407,
      406,  405,  404,  403,  402,  401,  400,  399,  398,  397,
      396,  395,  394,  393,  392,  391,  390,  389,  388,  387,
      386,  385,  384,  383,  382,  381,  380,  379,  378,  377,
      376,  375,  374,  373,  372,  371,  370,  369,  368,  367,
      366,  365,  364,  363,  362,  361,  360,  359,  358,  357,

      355,  353,  352,  339,  338,  337,  336,  335,  334,  333,
      332,  331,  330,  329,  328,  327,  326,  325,  324,  323,
      322,  321,  320,  319,  318,  317,  316,  315,  314,  313,
      312,  311,  310,  309,  308,  307,  306,  305,  304,  303,
      302,  301,  300,  299,  298,  297,  296,  295,  294,  293,
      292,  291,  290,  289,  270,  269,  268,  267,  266,  265,
      264,  263,  262,  261,  260,  259,  258,  257,  256,  255,
      254,  253,  252,  251,  250,  249,  248,  247,  246,  245,
      244,  243,  242,  241,  240,  239,  238,  237,  236,  235,
      234,  233,  213,  212,  211,  210,  209,  208,  207,  206,

      205,  204,  203,  202,  201,  200,  199,  198,  197,  196,
      195,  194,  193,  192,  191,  190,  189,  188,  187,  168,
      167,  166,  165,  164,  163,  162,  161,  160,  159,  158,
      157,  156,  155,  154,  153,  152,  151,  132,  131,  130,
      129,  128,  127,  126,  125,  124,  123,  122,   98,   97,
       96,   95,   94,   93,   91,   90,   89,   88,   87,   86,
       85,   83,   66,   65,   64,   62,   61,   60,   57,   55,
       40,   36,   34,   33,   32,   30,   29,   28,   26,   25,
       14,    8,    6,    3,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,

      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 ".\\lexico.lex"
#define INITIAL 0

#line 7 ".\\lexico.lex"
    #include <stdio.h>
    #include <stdlib.h>
    #include <string.h>
    FILE *arq;
#line 744 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 50 ".\\lexico.lex"


#line 898 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 426 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 885 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 52 ".\\lexico.lex"
{fprintf(arq, "ABRE_PARENTESES: %s\n", yytext);}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 53 ".\\lexico.lex"
{fprintf(arq, "ATRIBUICAO: %s\n", yytext);}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 54 ".\\lexico.lex"
{fprintf(arq, "ENQUANTO: %s\n", yytext);}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 55 ".\\lexico.lex"
{fprintf(arq, "ENTAO: %s\n", yytext);}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 56 ".\\lexico.lex"
{fprintf(arq, "ESCREVA: %s\n", yytext);}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 57 ".\\lexico.lex"
{fprintf(arq, "ERRO: %s\n", yytext);}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 58 ".\\lexico.lex"
{fprintf(arq, "FACA: %s\n", yytext);}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 59 ".\\lexico.lex"
{fprintf(arq, "FECHA_PARENTESES: %s\n", yytext);}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 60 ".\\lexico.lex"
{fprintf(arq, "FIMENQ: %s\n", yytext);}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 61 ".\\lexico.lex"
{fprintf(arq, "FIMPROG: %s\n", yytext);}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 62 ".\\lexico.lex"
{fprintf(arq, "FIMSE: %s\n", yytext);}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 63 ".\\lexico.lex"
{}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 64 ".\\lexico.lex"
{fprintf(arq, "TIPO: %s\n", yytext);}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 65 ".\\lexico.lex"
{fprintf(arq, "LEIA: %s\n", yytext);}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 66 ".\\lexico.lex"
{fprintf(arq, "TIPO: %s\n", yytext);}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 67 ".\\lexico.lex"
{fprintf(arq, "TIPO: %s\n", yytext);}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 68 ".\\lexico.lex"
{fprintf(arq, "MENSAGEM: %s\n", yytext);}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 69 ".\\lexico.lex"
{fprintf(arq, "NUMERO: %s\n", yytext);}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 70 ".\\lexico.lex"
{fprintf(arq, "NUMERO_REAL: %s\n", yytext);}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 71 ".\\lexico.lex"
{fprintf(arq, "OPERADOR_ARITMETICO: %s\n", yytext);}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 72 ".\\lexico.lex"
{fprintf(arq, "OPERADOR_LOGICO: %s\n", yytext);}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 73 ".\\lexico.lex"
{fprintf(arq, "OPERADOR_LOGICO_NEG: %s\n", yytext);}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 74 ".\\lexico.lex"
{fprintf(arq, "OPERADOR_RELACIONAL: %s\n", yytext);}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 75 ".\\lexico.lex"
{fprintf(arq, "PROGRAMA: %s\n", yytext);}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 76 ".\\lexico.lex"
{fprintf(arq, "TIPO: %s\n", yytext);}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 77 ".\\lexico.lex"
{fprintf(arq, "SE: %s\n", yytext);}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 78 ".\\lexico.lex"
{fprintf(arq, "SENAO: %s\n", yytext);}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 79 ".\\lexico.lex"
{fprintf(arq, "VARIAVEL: %s\n", yytext);}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 80 ".\\lexico.lex"
{fprintf(arq, "VARIAVEL_LISTA: %s\n", yytext);}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 81 ".\\lexico.lex"
{fprintf(arq, "SEPARADOR: %s\n", yytext);}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 83 ".\\lexico.lex"
ECHO;
	YY_BREAK
#line 1136 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 426 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 426 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 425);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 83 ".\\lexico.lex"


int yywrap();

int main(){
    if(!(arq = fopen ("tokens.txt", "w"))){
        printf ("Arquivo inexistente.\n");
        return 0;
   	}
    yylex();
    fclose(arq);
	return 0;
}

int yywrap () { return 1;}
